#!/usr/bin/env bash

cd $HOME/Eagle

## Print Colorful
# Print text in red
prtred() {
  printf '\e[1;31m%s\n\e[0;39;49m' "$@"
}
# Pri
# Print text in green
prtgrn() {
  printf '\e[1;32m%s\n\e[0;39;49m' "$@"
}
# Print text in brown
prtbrown() {
  printf '\e[1;33m%s\n\e[0;39;49m' "$@"
}
# update data to the last versio


install() {
	    cd data
		sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
		sudo apt-get install g++-4.7 -y c++-4.7 -y
		sudo apt-get update
		sudo apt-get upgrade
						prtgrn "
[»» install bot stating ««] 
"
		sudo apt-get install libreadline-dev -y libconfig-dev -y libssl-dev -y lua5.2 -y liblua5.2-dev -y lua-socket -y lua-sec -y lua-expat -y libevent-dev -y make unzip git redis-server autoconf g++ -y libjansson-dev -y libpython-dev -y expat libexpat1-dev -y     
		prtgrn "
[»» ᴜᴘᴅᴀᴛɪɴɢ ᴘᴀᴄᴋᴀɢᴇs ««] 
"
		sudo apt-get install screen -y
		sudo apt-get install tmux -y
		sudo apt-get install libstdc++6 -y
		sudo apt-get install lua-lgi -y
				prtgrn "
[»» ᴄᴏɴғɪɢ ʜᴀs ʙᴇᴇɴ ᴄʀᴇᴀᴛᴇᴅ ««] 
"
		sudo apt-get install libnotify-dev -y
		sudo service redis-server restart
		wget https://www.teameagle.ir/Telegrambot_sam/telegrambot
		mv telegrambot Telegrambot
		chmod +x Telegrambot
		cd ..
		chmod +x data
				prtgrn "
[»» install telegrambot ««] 
"
}

if [ "$1" = "install" ]; then
  install
  else

if [ ! -f ./data/Telegrambot ]; then
    echo "Telegrambot not found"
    echo "Run $0 install"
    exit 1
 fi

   #sudo service redis-server restart
   #./data/Telegrambot -s ./SUDO_CLI.lua -l 1 -E $@
   ./data/Telegrambot -s ./SUDO_CLI.lua $@
fi
